version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-layer-frontend

  api-layer-frontend:
    build: ./api-layer-frontend
    ports:
      - "5001:5001"
    depends_on:
      - product-domain
      - payment-domain

  product-domain:
    build: ./product-domain
    ports:
      - "5002:5002"
    volumes:
      - ./db/product:/app/db
    depends_on:
      - api-layer-ai

  payment-domain:
    build: ./payment-domain
    ports:
      - "5003:5003"
    volumes:
      - ./db/payment:/app/instance
    depends_on:
      - api-layer-ai

  api-layer-ai:
    build: ./api-layer-ai
    ports:
      - "5004:5004"
    depends_on:
      - ai-domain
  
  ai-domain:
    build: ./ai-domain
    ports:
      - "5005:5005"
