version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-layer

  api-layer-frontend:
    build: ./api-layer-frontend
    ports:
      - "5001:5001"
    depends_on:
      - product-domain
      - payment-domain

  product-domain:
    build: ./product-domain
    ports:
      - "5002:5002"
    volumes:
      - ./db/product:/app/db

  payment-domain:
    build: ./payment-domain
    ports:
      - "5003:5003"
    volumes:
      - ./db/payment:/app/instance
